role_bi_hostname_default_domain: "mauerpark-l105-vm.heinlein-intern.de"
# role_bi_repositories_repolist_debian:
#   - repo: 'deb https://packages.grafana.com/enterprise/deb stable main'
#     filename: 'Grafana-Test'
#     key_url: 'https://packages.grafana.com/gpg.key'
# role_bi_hostname.etc_hosts_entries:
#   "127.0.0.1": "localhost localhost.localdomain localhost4 localhost4.localdomain4"
#   "::1": "localhost localhost.localdomain localhost6 localhost6.localdomain6"
#   192.168.122.10: ansible-master.hoppetosse.local ansible-master
#   192.168.122.20: elk.hoppetosse.local elk
#   192.168.122.40: acs-management.hoppetosse.local acs-management

